config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  resources :questions do
    resources :answers do
      post 'mark_best', on: :member
    end
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v0 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers
      end
    end
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true

  mount_uploader :file, FileUploader
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!
  
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy if @attachment.attachable.user == current_user
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_attachment.html.slim
p.mb-2 Attachments:
= f.fields_for :attachments do |a|
  .form-group
    = render 'attachments/attachment_fields', a: a
  = link_to_add_association 'add another file', f, :attachments,
          partial: 'attachments/attachment_fields', form_name: :a,
          render_options: { wrapper: 'inline' }

app/views/attachments/_attachment_fields.html.slim
.form-group.nested-fields
  = a.label :file
  = a.file_field :file, class: 'form-control-file mb-3'
/  = link_to_remove_association "remove file", a

app/views/attachments/_single_attachment.html.slim
.single-attachment
  = link_to a.file.url, class: 'file' do
    = fa_icon 'file'
    p= a.file.file.filename
  - if can?(:update, a)
    = link_to attachment_path(a), method: :delete, remote: true, class: 'remove-file' do
      = fa_icon 'times-circle'

app/views/attachments/destroy.js.erb
$('a.remove-file').bind('ajax:success', function (e) {
    $(this).closest('.single-attachment').fadeOut()

})