config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  resources :questions do
    resources :answers do
      post 'mark_best', on: :member
    end
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v0 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true
  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachable
  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  default_scope { order(best: :desc, created_at: :asc) }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question
  before_action :load_answer, only: %i[destroy update mark_best]

  authorize_resource

  def create
    @answer = @question.answers.build(answer_params.merge({ user: current_user }))
    @answer.save
  end

  def destroy
    if @answer.user == current_user
      @answer.destroy
    end
  end

  def update
    if @answer.user == current_user
      @answer.update(answer_params)
    end
  end

  def mark_best
    authorize! :mark_best, @answer, user: @question.user
    if @question.user == current_user
      @question.make_best(@answer)
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/api/v0/answers_controller.rb
class Api::V0::AnswersController < Api::V0::BaseController
  before_action :doorkeeper_authorize!, only: %w(create)
  before_action :load_question, only: %w(show index create)

  def index
    render json: @question.answers
  end

  def create
    @answer = @question.answers.build(answer_params.merge({ user: current_resource_owner }))
    if (@answer.save)
      render json: @answer, status: 201
    else
      render json: @answer.errors.full_messages.to_json, status: 400
    end
  end

  def show
    render json: @question.answers.find(params[:id])
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.col-12.single-answer.p-0.mt-2
  - if can?(:update, answer)
    = link_to 'delete', question_answer_path(@question, answer), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'delete btn btn-danger'
    = link_to 'edit', '', class: 'edit btn btn-primary', data: { answer_id: answer.id }
  h5= "#{answer.user.first_name} #{answer.user.last_name}"
  - if answer.best?
    = fa_icon 'check-square', class: 'best'
  - if can?(:mark_best, answer) && !answer.best?
    = link_to 'mark as best', mark_best_question_answer_path(@question, answer), method: :post, remote: true, class: 'btn btn-success mark-best', data: { answer_id: answer.id }
  p= "Posted on #{answer.created_at.strftime("%d %b, %Y")}"
  p.body.underline= answer.body
  - answer.attachments.each do |a|

    = render 'attachments/single_attachment', a: a
  = form_with model: [@question, answer], html: { id: "edit-answer-#{answer.id}" }, class: "mt-2 mb-2" do |f|
    .answer-errors
    = f.label :body, 'Your answer'
    = f.text_area :body, class: 'form-control pt-2 pb-2'
    = render 'attachments/attachment', f: f
    .form-group
      = f.submit 'Save', class: 'btn btn-success mt-2'

app/views/answers/_answers.html.slim
- @question.answers.each do |answer|
  = render 'answers/answer', answer: answer

app/views/answers/create.js.erb
$('#add-answer textarea')[0].value = ''
<% if @answer.errors.present? %>
  $('.add-answer-errors')[0].innerHTML = ''
  <% @answer.errors.full_messages.each do |message| %>
    $('.add-answer-errors')[0].innerHTML += '<p class="alert alert-danger"><%= message %></p>'
  <% end %>
<% else %>
  $('.answers')[0].innerHTML += '<%= j render 'answers/answer', answer: @answer %>'
<% end %>

app/views/answers/destroy.js.erb
$('.single-answer .delete').bind('ajax:success', function (e) {
  $(this).closest('.single-answer').fadeOut()
})

app/views/answers/mark_best.js.erb
$('.answers')[0].innerHTML = '<%= j render 'answers/answers' %>'

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  $('#edit-answer-<%= @answer.id %> > .answer-errors')[0].innerHTML = ''
  <% @answer.errors.full_messages.each do |message| %>
  $('#edit-answer-<%= @answer.id %> > .answer-errors')[0].innerHTML += '<p class="alert alert-danger"><%= message %></p>'
  <% end %>
<% else %>
  $('.answers')[0].innerHTML = '<%= j render 'answers/answers' %>'
  $('.single-answer .edit').click(function (e) {
      e.preventDefault()
      $(this).hide()
      const answer_id = $(this).data('answerId')
      $('form#edit-answer-' + answer_id).show()
      $('form#edit-answer-' + answer_id).closest('.body').hide()
  })
<% end %>