config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  resources :questions do
    resources :answers do
      post 'mark_best', on: :member
    end
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v0 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers
      end
    end
  end
end

app/views/common/_footer.html.slim
.container-fluid.footer
  .container
    .row
      .col-md-4.text-left
        p
          | Copyright © 2020 Dmytro Havrysh

app/views/common/_header.html.slim
.container-fluid.login-nav
  - if notice.present?
    p.notice.alert.alert-success.notification= notice
  - if alert.present?
    p.alert.alert-danger.notification= alert
  .container
    .nav.text-right
      - if user_signed_in?
        - if current_user.admin?
        = link_to 'Register App for API', oauth_applications_path
        = link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        = link_to 'Sign in', new_user_session_path
        = link_to 'Sign up', new_user_registration_path
.container
  .row
    .col-12.logo-banner.text-center
      .row
        .col-md-6.offset-3.text-center.mb-4.mt-4
          a href='/'
            h1
              | Stackover
              span.blue
                | blow
.container-fluid.main-nav
  .container
    .row
      .col-md-6.offset-3.menu
        .row
          = link_to 'Home', root_path, :class => current_class?(root_path)
          = link_to 'Ask question', new_question_path, :class => current_class?(new_question_path)
          = link_to 'Help', root_path, :class => current_class?(new_user_session_path)

app/views/common/_search.html.slim
.container-fluid.search-form
  .container
    .row
      .col-md-6.offset-3.text-center.mb-4.mt-4
        h2
          | Have a question?
        p
          | solve your problem in few minutes
        /!
          form.mb-4.mt-4
            input type='text' name='search' placeholder='What do you need help with?'
            button.hover-btn type='submit'
              | Search

app/views/common/_side_bar.html.slim
.row
  .col-12.mt-4
    h3.underline Popular questions
    ul
      li
        = link_to 'Question 1', root_path
      li
        = link_to 'Question 1', root_path
      li
        = link_to 'Question 1', root_path
      li
        = link_to 'Question 1', root_path